name: Update the repository

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

env:
  WARPBUILD_CACHE_REF: v1.4.11

jobs:
  update:
    name: Update the repository (${{ matrix.reference }}${{ matrix.suffix }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        reference: [v5]
        suffix: [""]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Establish the committer identity
        continue-on-error: false
        run: |
          git config --global user.name "Cache Wrapper"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Add "actions/cache" as a Git remote and fetch it
        continue-on-error: false
        run: |
          git remote add upstream https://github.com/actions/cache.git
          git fetch upstream --tags --force
          git remote add warpbuilds https://github.com/WarpBuilds/cache.git
          git fetch warpbuilds "refs/tags/${WARPBUILD_CACHE_REF}:refs/remotes/warpbuilds/cache" --force

      - name: Checkout to a new branch ${{ matrix.reference }}${{ matrix.suffix }} that is pointing to ${{ matrix.reference }}
        continue-on-error: false
        run: |
          git checkout -B ${{ matrix.reference }}${{ matrix.suffix }} ${{ matrix.reference }}

      - name: Remove the workflow directory
        continue-on-error: false
        run: |
          rm -rf .github/workflows

      - name: Apply cache wrapper modifications
        continue-on-error: false
        run: |
          git show ${{ github.sha }}:trampoline${{ matrix.suffix }}.mjs > dist/restore/trampoline.mjs
          git show ${{ github.sha }}:trampoline${{ matrix.suffix }}.mjs > dist/restore-only/trampoline.mjs
          git show ${{ github.sha }}:trampoline${{ matrix.suffix }}.mjs > dist/save/trampoline.mjs
          git show ${{ github.sha }}:trampoline${{ matrix.suffix }}.mjs > dist/save-only/trampoline.mjs
          git show refs/remotes/warpbuilds/cache:dist/restore/index.js > dist/restore/warp-index.js
          git show refs/remotes/warpbuilds/cache:dist/restore-only/index.js > dist/restore-only/warp-index.js
          git show refs/remotes/warpbuilds/cache:dist/save/index.js > dist/save/warp-index.js
          git show refs/remotes/warpbuilds/cache:dist/save-only/index.js > dist/save-only/warp-index.js
          sed -i 's/index.js/trampoline.mjs/' action.yml restore/action.yml save/action.yml

      - name: Commit and push the changes
        continue-on-error: false
        run: |
          git add . && git commit -m "Cache wrapper modifications"

      - name: Force-push to the "${{ matrix.reference }}${{ matrix.suffix }}" branch
        run: git push -f origin refs/heads/${{ matrix.reference }}${{ matrix.suffix }}
